### ISSUE TITLE
Issue using 128 bit UUID

### ISSUE THREAD

**Issue by DucampGaspard** [Velorexe/Unity-Android-Bluetooth-Low-Energy#9]
Hello @Velorexe,

First of all, thank you for this repo, I'm new to both Unity and BLE and since I'm working on a project where I need to establish a BLE communication between a device and an android based application, it is really helpful.

I'm having some hard time trying to subscribe to my device characteristic using your example. The services and characteristics related to my issue are defined as follow : 

```
private string UUID_PROCESSING_SERVICE = "c2890001-ca9a-11eb-b8bc-0242ac130003";
private string UUID_CHARACTERISTIC_PROCESSING = "c2890002-ca9a-11eb-b8bc-0242ac130003";

private string UUID_BATTERY_SERVICE = "0000180f-0000-1000-8000-00805f9b34fb";
private string UUID_CHARACTERISTIC_BATTERY_LEVEL = "00002a19-0000-1000-8000-00805f9b34fb";
```

I don't have any issue subscribing to the battery characteristic using:

```
BleManager.Instance.QueueCommand(new SubscribeToCharacteristic(_deviceUuid, UUID_BATTERY_SERVICE.Get16BitUuid(), UUID_CHARACTERISTIC_BATTERY_LEVEL.Get16BitUuid());
```

However, when I try to subscribe to the processing characteristic using the following code :

```
BleManager.Instance.QueueCommand(new SubscribeToCharacteristic(_deviceUuid, UUID_PROCESSING_SERVICE, UUID_CHARACTERISTIC_PROCESSING);
```

I have the following error : 

```
AndroidJavaException: java.lang.IllegalArgumentException: Invalid UUID string: 0000c2890001-ca9a-11eb-b8bc-0242ac130003-0000-1000-8000-00805f9b34fb
````

Is there a way to use 128 bits UUID within your code (it doesn't work either using Get16BitUuid()) ? Am I missing something ?

Sorry for the inconvenience and if the question isn't clear !

**Comment by Velorexe** [comment]
Hey @DucampGaspard 

You didn't miss anything, this is a mistake on my part! In the `SubscribeToCharacteristic` class there's a check to see if a UUID is a short 16-bit UUID, since most BLE services and characteristics only differ in the first 16-bits.

So I've added a `_customGatt` field to most commands that interact with services and characteristics to see if it's a custom GATT UUID (128-bit) or short UUID (16-bit). At the `Start()` it checks if the `_customGatt` field is true or not, but this field is not set in the constructor.

I'll roll out a fix in around an hour or so!

**Comment by Velorexe** [comment]
Also I just realized that I keep using the term 16-bit, even though it's supposed to be 8 bit. I'll push that as a change as well haha

**Comment by DucampGaspard** [comment]
Thanks a lot, it works perfectly now ! 😊

Regarding the subscription to multiple characteristics, it seems that I receive notifications only for the first one, e.g. : 

- the battery info if I do :

```
BleManager.Instance.QueueCommand(new SubscribeToCharacteristic(_deviceUuid, UUID_BATTERY_SERVICE.Get8BitUuid(), UUID_CHARACTERISTIC_BATTERY_LEVEL.Get8BitUuid());

BleManager.Instance.QueueCommand(new SubscribeToCharacteristic(_deviceUuid, UUID_PROCESSING_SERVICE, UUID_CHARACTERISTIC_PROCESSING, true));
```

- the result of the processing (an integer) if I first subscribe to this characteristic. 

Can we have concurrent subscriptions and notifications, or just one at the time ?

**Comment by Velorexe** [comment]
Interesting, from what I see there shouldn't be a reason why 2 concurrent subscriptions shouldn't work. There are 2 constructors for the `SubscribeToCharacteristic` class, one where you can also add a method that needs to execute when the Characteristic updates it's value. Could you try that one with both? Pass in a simple lambda like

 `(x) => Debug.Log("Battery" + x.Length)` for both methods to see if they're updating.

I'll also setup a local BLE server with two subscribe Characteristics to see if I can reproduce the issue.

**Comment by Velorexe** [comment]
Alright, so I found a wrong check inside the `CommandReceived` method of `SubscribeToCharacteristic`, perhaps this should fix the issue that you were having. It has been pulled in to development ( #12 )

**Comment by DucampGaspard** [comment]
Regarding this function I think there is an issue as well line 59 (and 68) where you check for :

```
string.Equals(obj.Service, DeviceAddress) &&
```

instead of 

```
string.Equals(obj.Service, Service) &&
```

Nevertheless, and with this changed, I still can't manage to get both messages simultaneously.

**Comment by Velorexe** [comment]
Haha, must have written this code when sleep deprived or something. This afternoon I'll have a fix for you, I'll have access to the BLE server by then.

**Comment by DucampGaspard** [comment]
Hahaha no problem and thank you for your reactivity ! 

I have another question regarding the `BleObject.GetByteMessage()` function, at the moment it's defined as follows :

`
public byte[] GetByteMessage() => Convert.FromBase64String(command);
`

Shouldn't we convert the `base64_message` attribute of the received message ? For example using something like :
 
```
#region Message
public string Message => base64_message;
[SerializeField]
private string base64_message = string.Empty;
#endregion

public byte[] GetByteMessage() => Convert.FromBase64String(base64_message);
```

**Comment by Velorexe** [comment]
Yeah, seems like when I rewrote the project I forgot to add the `base64message` field, since that is given by received JSON. 
Good catch!
